package com.szeba.wyv.data;

/**
 * A set of parameters generated by widgets.
 * @author Szeba
 */
public class Signal {
	
	public static final int T_DEFAULT = 0;
	public static final int T_NEWMAP = 1;
	public static final int T_DROPLIST = 2;
	public static final int T_DIRLIST = 3;
	public static final int T_COMMAND_CHOOSER = 30;
	public static final int T_COMMAND_EDIT = 31;
	public static final int T_TPICK = 70;
	public static final int T_DELETE = 80;
	public static final int T_RENAME = 81;
	public static final int T_EDIT = 82;
	public static final int T_COPY = 83;
	public static final int T_CUT = 84;
	public static final int T_PASTE = 85;
	public static final int T_RENAME_MAP = 86;
	public static final int T_JUMP_COORD = 100;
	public static final int T_SEARCH_PLACE = 101;
	public static final int T_COMMON_EVENT = 200;
	public static final int T_COMMON_EVENT_EDIT = 201;
	public static final int T_DYN_DONE = 300;
	public static final int T_DYN_CANCEL = 301;
	public static final int T_INVALID_DIRLIST = 400;
	
	private int type;
	private String[] parameters;
	
	public Signal(int type, String... parameters) {
		this.type = type;
		this.parameters = parameters;
	}
	
	public int getType() {
		return type;
	}
	
	public String getParam(int index) {
		if (parameters.length > 0 && index < parameters.length) {
			return parameters[index];
		}
		return null;
	}
	
	public void setParam(int index, String value) {
		parameters[index] = value;
	}
	
	public int getLength() {
		return parameters.length;
	}
	
}
